---
- name: Configure VyOS
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
    ansible_user: vyos
    ansible_network_os: vyos.vyos.vyos
    ansible_ssh_timeout: 120
    ansible_command_timeout: 120
    pause_time: 1
  hosts: router

  tasks:
    - name: Set hostname
      vyos.vyos.vyos_config:
        lines:
          - set system host-name '{{ ansible_hostname }}'
      tags: hostname
      when: os == "vyos"

    - pause:
        seconds: "{{ pause_time }}"

    - name: Set interfaces
      vyos.vyos.vyos_config:
        lines:
          - set interfaces {{ item.interface_type }} {{ item.interface }} address '{{ item.ipv4_address }}'
          - delete interfaces {{ item.interface_type }} {{ item.interface }} hw-id
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.interface }}"
      tags: interfaces
      when: os == "vyos"

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure static routes
      vyos_config:
        lines:
          - set protocols static route {{ item.destination }} next-hop {{ item.next_hop }} distance {{ item.distance | default(1) }}
      loop: "{{ hostvars[inventory_hostname].static_routes | default([]) }}"
      when: os == "vyos" and static_routes is defined
      tags: static_routes

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure name-server
      vyos_config:
        lines:
          - set system name-server 1.1.1.1
      tags: nameserver
      when: os == "vyos"

    - pause:
        seconds: "{{ pause_time }}"

    - block:
        - name: Configure MPLS interfaces
          vyos_config:
            lines:
              - set protocols mpls interface {{ item.interface }}
          loop: "{{ mpls.interfaces }}"
          loop_control:
            label: "{{ item.interface }}"

        - pause:
            seconds: "{{ pause_time }}"

        - name: Configure MPLS LDP interfaces
          vyos_config:
            lines:
              - set protocols mpls ldp router-id {{ mpls.ldp.router_id }}
              - set protocols mpls ldp discovery transport-ipv4-address {{ mpls.ldp.router_id }}
              - set protocols mpls ldp interface {{ item.interface }}
          loop: "{{ mpls.ldp.interfaces }}"
          loop_control:
            label: "{{ item.interface }}"
      tags: mpls
      when: os == "vyos" and mpls is defined

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure OSPF parameters
      vyos_config:
        lines:
          - set protocols ospf parameters router-id {{ ospf.router_id }}
      tags: ospf
      when: os == "vyos"

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure OSPF interface and area
      vyos_config:
        lines:
          - set protocols ospf area {{ ospf.v4.area }} network {{ item.network }}
          - set protocols ospf interface {{ item.interface }}
      loop: "{{ ospf.v4.interfaces }}"
      loop_control:
        label: "{{ item.interface }}"
      tags: ospf
      when: os == "vyos"

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure OSPF default information
      vyos_config:
        lines:
          - set protocols ospf default-information originate {{ ospf.v4.default_information }}
      tags: ospf
      when: os == "vyos" and ospf.v4.default_information is defined

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure BGP parameters
      vyos_config:
        lines:
          - set protocols bgp parameters router-id {{ bgp.router_id }}
          - set protocols bgp system-as {{ bgp.as }}
      tags: bgp
      when: os == "vyos"

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure BGP networks
      vyos_config:
        lines:
          - set protocols bgp address-family ipv4-unicast network {{ item }}
      with_items: "{{ bgp.networks.ipv4_unicast }}"
      tags: bgp
      when: os == "vyos" and bgp.networks is defined

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure BGP neighbors rr client
      vyos_config:
        lines:
          - set protocols bgp neighbor {{ item.ipv4_address }} address-family ipv4-unicast nexthop-self
          - set protocols bgp neighbor {{ item.ipv4_address }} remote-as {{ item.remote_as }}
          - set protocols bgp neighbor {{ item.ipv4_address }} update-source {{ item.update_source }}
          - set protocols bgp neighbor {{ item.ipv4_address }} description {{ item.description }}
      loop: "{{ bgp.neighbors_rr_client }}"
      loop_control:
        label: "{{ item.ipv4_address }}"
      tags: bgp
      when: os == "vyos" and bgp.neighbors_rr_client is defined

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure BGP neighbors rr server
      vyos_config:
        lines:
          - set protocols bgp neighbor {{ item.ipv4_address }} address-family ipv4-unicast route-reflector-client
          - set protocols bgp neighbor {{ item.ipv4_address }} remote-as {{ item.remote_as }}
          - set protocols bgp neighbor {{ item.ipv4_address }} update-source {{ item.update_source }}
          - set protocols bgp neighbor {{ item.ipv4_address }} description {{ item.description }}
      loop: "{{ bgp.neighbors_rr_server }}"
      loop_control:
        label: "{{ item.ipv4_address }}"
      tags: bgp
      when: os == "vyos" and bgp.neighbors_rr_server is defined

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure BGP neighbors rr peer
      vyos_config:
        lines:
          - set protocols bgp parameters cluster-id {{ item.cluster_id }}
          - set protocols bgp neighbor {{ item.ipv4_address }} address-family ipv4-unicast
          - set protocols bgp neighbor {{ item.ipv4_address }} remote-as {{ item.remote_as }}
          - set protocols bgp neighbor {{ item.ipv4_address }} update-source {{ item.update_source }}
          - set protocols bgp neighbor {{ item.ipv4_address }} description {{ item.description }}
      loop: "{{ bgp.neighbors_rr_peer }}"
      loop_control:
        label: "{{ item.ipv4_address }}"
      tags: bgp
      when: os == "vyos" and bgp.neighbors_rr_peer is defined

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure BGP neighbors
      vyos_config:
        lines:
          - set protocols bgp neighbor {{ item.ipv4_address }} address-family ipv4-unicast
          - set protocols bgp neighbor {{ item.ipv4_address }} remote-as {{ item.remote_as }}
          - set protocols bgp neighbor {{ item.ipv4_address }} update-source {{ item.update_source }}
          - set protocols bgp neighbor {{ item.ipv4_address }} description {{ item.description }}
      loop: "{{ bgp.neighbors }}"
      loop_control:
        label: "{{ item.ipv4_address }}"
      tags: bgp
      when: os == "vyos" and bgp.neighbors is defined

    - pause:
        seconds: "{{ pause_time }}"

    - name: Configure NAT
      vyos_config:
        lines:
          - set nat {{ nat.type }} rule 1 outbound-interface name '{{ nat.interface }}'
          - set nat {{ nat.type }} rule 1 translation address '{{ nat.translation }}'
      tags: nat
      when: os == "vyos" and nat is defined

    - pause:
        seconds: 3

    - name: Save config
      vyos_config:
        save: true
      tags: save
